name: flutter_simple_carousel
description: "A simple carousel widget for Flutter. Supports horizontal and vertical scrolling, automatic text direction handling, and more."
version: 0.0.3
homepage: https://github.com/bcheidemann/flutter_simple_carousel

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
